spring.datasource.url=jdbc:mysql://localhost:3306/metaports
spring.datasource.username=root
spring.datasource.password=0000

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>