server.address=175.106.97.249
server.port=22

# API ???, SQL ?? ??? ????.
spring.jpa.show-sql=true

# DDL ??? ??????? ?? ??? ?????.
# ex) ??? ??, ?? ?
spring.jpa.generate-ddl=true

# MySQL ? ??? ?.
spring.jpa.database=mysql

# MySQL ??
spring.datasource.url=jdbc:mysql://db-kl7j1.vpc-cdb.ntruss.com:3306/metaports
spring.datasource.username=djlee_991
spring.datasource.password=HumanF_99!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL ?? ??
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>